# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Yt1xQn59O3jmQ0_eEOMj5draKHZx-43
"""

n = 5
fact = 1
for i in range(1, n + 1):
    fact = fact * i
print(f"factorial of {n} is {fact}")