# -*- coding: utf-8 -*-
"""Fibonacci and Structure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qa2fqczZv_VFVt9f-o8pFP04H-rquz1_
"""

n = int(input("Enter the number of terms: "))

t1 = 0
t2 = 1

nextTerm = t1 + t2

print(f"Fibonacci Series: {t1}, {t2}, ", end="")

for i in range(3, n + 1):
    print(f"{nextTerm}, ", end="")

    t1 = t2
    t2 = nextTerm
    nextTerm = t1 + t2

class Student:
    def __init__(self, name: str, rollNo: int, avgMarks: float):
        self.name = name
        self.rollNo = rollNo
        self.avgMarks = avgMarks

student = Student("Rahul", 101, 85.5)

print("Student Details:")
print(f"Name: {student.name}")
print(f"Roll No: {student.rollNo}")
print(f"Average Marks: {student.avgMarks:.2f}")