# -*- coding: utf-8 -*-
"""largest_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-VaUJi_X7J8u6Jn3GZWDCA4ePGWsnQIV
"""

n1 = float(input("Enter first number: "))
n2 = float(input("Enter second number: "))
n3 = float(input("Enter third number: "))

if n1 >= n2 and n1 >= n3:
    largest = n1
elif n2 >= n1 and n2 >= n3:
    largest = n2
else:
    largest = n3

print(f"The largest number is {largest}")