# -*- coding: utf-8 -*-
"""Session 4_25BCON0907.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tn6goXfaWsCsK-snvXGPRjfrSwKv6qI
"""

print("Hello Collab")

n = 5
fact = 1
for i in range(1, n + 1):
    fact = fact * i
print(f"factorial of {n} is {fact}")

n = int(input("Enter the number of terms: "))

t1 = 0
t2 = 1

nextTerm = t1 + t2

print(f"Fibonacci Series: {t1}, {t2}, ", end="")

for i in range(3, n + 1):
    print(f"{nextTerm}, ", end="")

    t1 = t2
    t2 = nextTerm
    nextTerm = t1 + t2

class Student:
    def __init__(self):
        self.name = "Rahul"
        self.rollNo = 101
        self.Marks = 87.5


s1 = Student()

print("Student Details:")
print(f"Name: {s1.name}")
print(f"Roll No: {s1.rollNo}")
print(f"Marks: {s1.Marks:.2f}")