# -*- coding: utf-8 -*-
"""smallest_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPti2Pya178k5NZZxUUFV4m50quyNTSw
"""

a = 15
b = 7
c = 22

# Method 1: Using logic gates
if a <= b and a <= c:
    smallest = a
elif b <= a and b <= c:
    smallest = b
else:
    smallest = c

print(f"The smallest number is: {smallest}")