# -*- coding: utf-8 -*-
"""sum_2_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iu0kVNitqXXv5Or8kknti7gNX_rsUj1J
"""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))


total_sum = num1 + num2


print(f"The sum of {num1} and {num2} is {total_sum}")